server:
  port: 8088
spring:
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    cache: false
    mvc:
    static-path-pattern: /static/**
  ## Redis 配置
  redis: ## Redis数据库索引（默认为0）
   database: 0
  ## Redis服务器地址
   host: 127.0.0.1
  ## Redis服务器连接端口
   port: 6379
  ## Redis服务器连接密码（默认为空）
   password:
  ## 连接池最大连接数（使用负值表示没有限制）
   maxTotal: 100
  #最大空闲数
   maxIdle: 30
  ## 连接超时时间（毫秒）
   timeout: 1200
# OAuth 登录校验相关
customUrl:
 # gitHubOAuth: https://github.com/login/oauth/authorize?client_id=3b000897bad3167eb3fc
 gitHubOAuth: https://github.com/login/oauth/authorize?client_id=b0d6f08715b5fe5bb182
 userIfoUrl: https://api.github.com/user?access_token=
 userTockenUrl: https://github.com/login/oauth/access_token
 # clientSecret: 0d5fc5878c8477f7d226b4ea91a0525e327e624e
 clientSecret: fdbe0d19599a48b6b7dacfe38e17d3455e233313
 # clientId: 3b000897bad3167eb3fc
 clientId: b0d6f08715b5fe5bb182
# 百度POI获取相关
poiSearch:
  # 百度Map应用 ak
 ak: YLe7rt4r0SeL023VjjktUpDsIGbt9phU
 # 最近距离排序
 filter: sort_name:distance|sort_rule:1
 # 搜索范围 5 公里圆形区域
 radius: 5000
 geoCoderUrl: http://api.map.baidu.com/geocoder/v2/
 poiSearchUrl: http://api.map.baidu.com/place/v2/search
 poiName1: 福特4S店
 poiName2: 中石化加油站

